spring.application.name=ticketing-backend
# URL-ul de conectare. Fi?ierul ticketing.db va fi creat automat în folderul r?d?cin? al proiectului
spring.datasource.url=jdbc:sqlite:ticketing.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Îi spunem lui Hibernate (modulul de date) s? foloseasc? dialectul de SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Aceast? setare este crucial?: creeaz? sau actualizeaz? tabelele automat pe baza claselor tale Java
spring.jpa.hibernate.ddl-auto=update

# Afi?eaz? comenzile SQL în consol?. Te va ajuta s? vezi exact ce "magie" face Spring în fundal
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080
